objects/Flosum__Branch__c.object
<CustomObject><fields><fullName>SCA_Integration_Status__c</fullName><description>Work: W-000175
Summary: Static Code Analysis integration review status.</description><externalId>false</externalId><label>SCA Integration Status</label><required>false</required><trackFeedHistory>false</trackFeedHistory><trackHistory>false</trackHistory><trackTrending>false</trackTrending><type>Picklist</type><valueSet><restricted>true</restricted><valueSetDefinition><sorted>false</sorted><value><fullName>Pending</fullName><default>false</default><label>Pending</label></value><value><fullName>Queued</fullName><default>false</default><label>Queued</label></value><value><fullName>Successful</fullName><default>false</default><label>Successful</label></value><value><fullName>Failure</fullName><default>false</default><label>Failure</label></value></valueSetDefinition></valueSet></fields><fields><fullName>Has_Apex_Code__c</fullName><defaultValue>false</defaultValue><description>Work: W-000080
Summary: The value is automatically updated whenever new Apex Classes are added to the Branch.</description><externalId>false</externalId><inlineHelpText>The value is automatically updated whenever new Apex Classes are added to the Branch.</inlineHelpText><label>Has Apex Code</label><trackFeedHistory>false</trackFeedHistory><trackHistory>false</trackHistory><trackTrending>false</trackTrending><type>Checkbox</type></fields></CustomObject>

objects/SCA_Result__c.object
<CustomObject>
    <description>Work: W-000026
Summary: This object stores SCA Results for a branch.</description>
    <label>SCA Result</label>
    <nameField>
        <displayFormat>SR-{0000000}</displayFormat>
        <label>SCA Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCA Results</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>SCA_Review_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Work: W-000026
Summary: Lookup to SCA Review History</description>
        <label>SCA Review History</label>
        <referenceTo>SCA_Review_History__c</referenceTo>
        <relationshipLabel>SCA Results</relationshipLabel>
        <relationshipName>SCA_Results</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/SCA_Review_History__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Work: W-000026
Summary: This object stores SCA Reviews for a branch.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableLicensing>false</enableLicensing><enableReports>true</enableReports><enableSearch>false</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><fields><fullName>Branch__c</fullName><description>Work: W-000026
Summary: Master-Detail to Branch</description><externalId>false</externalId><label>Branch</label><referenceTo>Flosum__Branch__c</referenceTo><relationshipLabel>SCA Review History</relationshipLabel><relationshipName>SCA_Review_Histories</relationshipName><relationshipOrder>0</relationshipOrder><reparentableMasterDetail>false</reparentableMasterDetail><trackHistory>false</trackHistory><trackTrending>false</trackTrending><type>MasterDetail</type><writeRequiresMasterRead>true</writeRequiresMasterRead></fields><fields><fullName>SCA_Integration_Status__c</fullName><description>Work: W-000026
Summary: Static Code Analysis integration review status.</description><externalId>false</externalId><label>SCA Integration Status</label><required>false</required><trackHistory>false</trackHistory><trackTrending>false</trackTrending><type>Picklist</type><valueSet><restricted>true</restricted><valueSetDefinition><sorted>false</sorted><value><fullName>Pending</fullName><default>false</default><label>Pending</label></value><value><fullName>Queued</fullName><default>false</default><label>Queued</label></value><value><fullName>Successful</fullName><default>false</default><label>Successful</label></value><value><fullName>Failure</fullName><default>false</default><label>Failure</label></value></valueSetDefinition></valueSet></fields><label>SCA Review History</label><nameField><displayFormat>SCA-{0000000}</displayFormat><label>SCA Review Reference</label><trackHistory>false</trackHistory><type>AutoNumber</type></nameField><pluralLabel>SCA Review Histories</pluralLabel><sharingModel>ControlledByParent</sharingModel><visibility>Public</visibility></CustomObject>

objects/SCA_Violations__c.object
<CustomObject>
    <description>Work: W-000026
Summary:This object stores SCA violations for a SCA Result.</description>
    <label>SCA Violation</label>
    <nameField>
        <displayFormat>SV-{0000000}</displayFormat>
        <label>SCA Violations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCA Violations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>SCA_Result__c</fullName>
        <label>SCA Result</label>
        <referenceTo>SCA_Result__c</referenceTo>
        <relationshipLabel>SCA Violations</relationshipLabel>
        <relationshipName>SCA_Violations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

classes/SCAScanResultsTest.cls
/**
 * @group:SCA Review
 * @description: Test class is for SCAScanResults Class
 */
@isTest public class SCAScanResultsTest {
  /**
   * @description: Setup Test data
   */
  @testSetup static void dataSetup() {
    // Get test Admin profile user form testDataUtils class to runn as admin
    List<User> adminUser = TestDataUtils.getUsers(1);
    // Run as test system admin user
    System.runAs(adminUser[0]) {
      // Create Repository record
      List<Flosum__Repository__c> repositoryRecordList = TestDataUtils.getRepositories(1);
      insert repositoryRecordList;
      // Assign License to repository
      Flosum__Repository_Permission__c repositoryPermissionRecord =
          TestDataUtils.repoPermission(repositoryRecordList[0].id, adminUser[0].id);
      insert repositoryPermissionRecord;
      // Create a Branch Record
      List<Flosum__Branch__c> listBranchDetails = TestDataUtils.getBranches(1);
      listBranchDetails[0].Flosum__Repository__c = repositoryRecordList[0].id;
      listBranchDetails[0].Has_Apex_Code__c = False;
      insert listBranchDetails;
      // Create ReviewHistory Record
      List<SCA_Review_History__c> listOfReviewHistory = TestDataUtils.getReviewHistory(1);
      // listOfReviewHistory[0].SCA_Integration_Status__c = 'Success';
      listOfReviewHistory[0].Branch__c = listBranchDetails[0].Id;
      insert listOfReviewHistory;
      // Create SCA Result Record
      List<SCA_Result__c> scaResultList = new List<SCA_Result__c>();
      SCA_Result__c sca = new SCA_Result__c();
      sca.SCA_Review_History__c = listOfReviewHistory[0].Id;
      scaResultList.add(sca);
      insert scaResultList;
      // Create a ViolationRecord Record
      List<SCA_Violations__c> listViolationRecord = TestDataUtils.getViolationRecords(1);
      listViolationRecord[0].SCA_Result__c = scaResultList[0].id;
    }
  }

  /**
   * @description: Cover recordCreation and chatterPost methods coverage
   */
  @isTest static void recordCreationTest() {
    // Get test Admin profile user from testDataUtils class to run as admin
    User adminUser = TestUserUtils.createTestUser('System Administrator', '');
    String scaReviewHistory;
    string contents =
        'Action.cls,3,1,Avoid using global modifier,Best Practices,AvoidGlobalModifier!%!Action.cls,3,1,Missing ApexDoc comment,Documentation,ApexDoc!%!Action.cls,3,2,Avoid empty block statements.,Error Prone,EmptyStatementBlock!%!Action.cls,3,2,Missing ApexDoc comment,Documentation,ApexDoc!%!Action.cls,3,3,Avoid empty block statements.,Error Prone,EmptyStatementBlock';
    String message = 'Test';
    system.runAs(adminUser) {
      // clang-format off
      List<SCA_Review_History__c> scaHistory = [
          SELECT Id
		  FROM SCA_Review_History__c LIMIT 1
      ];
      // clang-format on
      scaReviewHistory = scaHistory[0].Id;
      // clang-format off
      List<SCA_Violations__c> scaViolation = [
          SELECT Id
          FROM SCA_Violations__c LIMIT 1
      ];
      // clang-format on
      SCAScanResults.chatterPost(scaHistory[0].Id, message);
      SCAScanResults.recordCreation(scaReviewHistory, contents);
      System.assertequals(scaHistory.size(), 1, 'There should be only 1 Review History');
    }
  }

  /**
   * @description: Cover catch block coverage
   */
  @isTest static void recordCreationExceptionTest() {
    // Get test Admin profile user from testDataUtils class to run as admin
    User adminUser = TestUserUtils.createTestUser('System Administrator', '');
    String scaReviewHistory;
    string contents =
        'Action.cls,3,1,Avoid using global modifier,Best Practices,AvoidGlobalModifier!%!Action.cls,CatchBlockCoverage,1,Missing ApexDoc comment,Documentation,ApexDoc!%!Action.cls,3,2,Avoid empty block statements.,Error Prone,EmptyStatementBlock!%!Action.cls,3,2,Missing ApexDoc comment,Documentation,ApexDoc!%!Action.cls,3,3,Avoid empty block statements.,Error Prone,EmptyStatementBlock';
    String message = 'Test';
    system.runAs(adminUser) {
      // clang-format off
      List<SCA_Review_History__c> scaHistory = [
          SELECT Id
          FROM SCA_Review_History__c LIMIT 1
      ];
      // clang-format on
      scaReviewHistory = scaHistory[0].Id;
      // clang-format off
      List<SCA_Violations__c> scaViolation = [
          SELECT Id
          FROM SCA_Violations__c LIMIT 1
      ];
      // clang-format on
      SCAScanResults.chatterPost(scaHistory[0].Id, message);
      SCAScanResults.recordCreation(scaReviewHistory, contents);
      System.assertequals(scaHistory.size(), 1, 'There should be only 1 Review History');
    }
  }
}