objects/SCA_Result__c.object
<CustomObject>
    <description>Work: W-000026
Summary: This object stores SCA Results for a branch.</description>
    <label>SCA Result</label>
    <nameField>
        <displayFormat>SR-{0000000}</displayFormat>
        <label>SCA Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCA Results</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>SCA_Review_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Work: W-000026
Summary: Lookup to SCA Review History</description>
        <label>SCA Review History</label>
        <referenceTo>SCA_Review_History__c</referenceTo>
        <relationshipLabel>SCA Results</relationshipLabel>
        <relationshipName>SCA_Results</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/SCA_Review_History__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Work: W-000026
Summary: This object stores SCA Reviews for a branch.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableLicensing>false</enableLicensing><enableReports>true</enableReports><enableSearch>false</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><fields><fullName>Branch__c</fullName><description>Work: W-000026
Summary: Master-Detail to Branch</description><externalId>false</externalId><label>Branch</label><referenceTo>Flosum__Branch__c</referenceTo><relationshipLabel>SCA Review History</relationshipLabel><relationshipName>SCA_Review_Histories</relationshipName><relationshipOrder>0</relationshipOrder><reparentableMasterDetail>false</reparentableMasterDetail><trackHistory>false</trackHistory><trackTrending>false</trackTrending><type>MasterDetail</type><writeRequiresMasterRead>true</writeRequiresMasterRead></fields><fields><fullName>SCA_Integration_Status__c</fullName><description>Work: W-000026
Summary: Static Code Analysis integration review status.</description><externalId>false</externalId><label>SCA Integration Status</label><required>false</required><trackHistory>false</trackHistory><trackTrending>false</trackTrending><type>Picklist</type><valueSet><restricted>true</restricted><valueSetDefinition><sorted>false</sorted><value><fullName>Pending</fullName><default>false</default><label>Pending</label></value><value><fullName>Queued</fullName><default>false</default><label>Queued</label></value><value><fullName>Successful</fullName><default>false</default><label>Successful</label></value><value><fullName>Failure</fullName><default>false</default><label>Failure</label></value></valueSetDefinition></valueSet></fields><label>SCA Review History</label><nameField><displayFormat>SCA-{0000000}</displayFormat><label>SCA Review Reference</label><trackHistory>false</trackHistory><type>AutoNumber</type></nameField><pluralLabel>SCA Review Histories</pluralLabel><sharingModel>ControlledByParent</sharingModel><visibility>Public</visibility></CustomObject>

objects/SCA_Violations__c.object
<CustomObject>
    <description>Work: W-000026
Summary:This object stores SCA violations for a SCA Result.</description>
    <label>SCA Violation</label>
    <nameField>
        <displayFormat>SV-{0000000}</displayFormat>
        <label>SCA Violations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCA Violations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Error_Description__c</fullName>
        <description>Work: W-000026
Summary:This field stores the Error Description of the file.</description>
        <label>Error Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Name__c</fullName>
        <description>Work: W-000026
Summary:This field stores the Name of the file.</description>
        <label>File Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <description>Work: W-000026
Summary:This field stores the Line number where the Violation occurred</description>
        <label>Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>Work: W-000026
Summary:This field stores rule violation priority.</description>
        <label>Priority</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <description>Work: W-000026
Summary:This field stores the Rule Set of the Violation</description>
        <label>Rule Set</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule__c</fullName>
        <description>Work: W-000026
Summary:This field stores the Rule Violation Name</description>
        <label>Rule</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SCA_Result__c</fullName>
        <label>SCA Result</label>
        <referenceTo>SCA_Result__c</referenceTo>
        <relationshipLabel>SCA Violations</relationshipLabel>
        <relationshipName>SCA_Violations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

classes/SCAScanResults.cls
/**
 * @group: SCA Review
 * @description: Webservice class to insert the SCA Result and SCA Violation Records
 * @testclass: SCAScanResultsTest
 */
@RestResource(urlMapping = '/SCAScanResults/*') global with sharing class SCAScanResults {
  private
  static final string SCA_REVIEW_HISTORY_STATUS_SUCCESS = 'Successful';
  private
  static final string SCA_REVIEW_HISTORY_STATUS_FAILURE = 'Failure';
  private
  static final string SCA_REVIEW_HISTORY_SUCCESS_MESSAGE = LABEL.SCA_REVIEW_HISTORY_SUCCESS;

  /**
   * @description: Creates the SCA result and SCA Violation records
   **/
  @HttpPost global static void recordCreation(String scaReviewHistory, String contents) {
    // List to store the Violation Records
    List<SCA_Violations__c> scaViolationRecordsList = new List<SCA_Violations__c>();
    // sObject Variable to update a SCA Review History
    SCA_Review_History__c scaReviewHistoryRecord = new SCA_Review_History__c();
    try {
      // Update the id and SCA integration status for SCA Review History record
      scaReviewHistoryRecord.id = scaReviewHistory;
      scaReviewHistoryRecord.SCA_Integration_Status__c = SCA_REVIEW_HISTORY_STATUS_SUCCESS;
      String[] csvFileLines;
      // Create the SCA Result Record
      SCA_Result__c scaResultRecord = new SCA_Result__c();
      scaResultRecord.SCA_Review_History__c = scaReviewHistory;
      // Check if its SCA_Result__c isCreateable
      if (Schema.sObjectType.SCA_Result__c.isCreateable()) {
        insert scaResultRecord;
      }
      // split the contents based on the unique identifier
      if (contents != null && !string.isEmpty(contents)) {
        csvFileLines = contents.split('!%!');
      }
      // check the size and create the SCA Violations records accordingly.
      if (csvFileLines != null && csvFileLines.size() > 0) {
        for (Integer i = 0; i < csvFileLines.size(); i++) {
          String[] csvRecordData = csvFileLines[i].split(',');
          if (csvRecordData.size() > 0) {
            SCA_Violations__c violationRecord = new SCA_Violations__c();
            violationRecord.File_Name__c = csvRecordData[0].trim();
            violationRecord.Priority__c = Integer.valueOf(csvRecordData[1].trim());
            violationRecord.Line_Number__c = Integer.valueOf(csvRecordData[2].trim());
            violationRecord.Error_Description__c = csvRecordData[3].trim();
            violationRecord.Rule_Set__c = csvRecordData[4].trim();
            violationRecord.Rule__c = csvRecordData[5].trim();
            violationRecord.SCA_Result__c = scaResultRecord.id;
            scaViolationRecordsList.add(violationRecord);
          }
        }
      }
      if (Schema.sObjectType.SCA_Violations__c.isCreateable()
          && Schema.sObjectType.SCA_Review_History__c.Isupdateable()) {
        if (scaViolationRecordsList.size() > 0) {
          insert scaViolationRecordsList;
        }
        update scaReviewHistoryRecord;
        chatterPost(scaReviewHistory, SCA_REVIEW_HISTORY_SUCCESS_MESSAGE);
      }
    } catch (Exception e) {
      scaReviewHistoryRecord.SCA_Integration_Status__c = SCA_REVIEW_HISTORY_STATUS_FAILURE;
      update scaReviewHistoryRecord;
      chatterPost(scaReviewHistory, string.ValueOf(e));
    }
  }

  /**
   * @description: Chatter post to branches which are submitted for SCA Review
   **/
  public
  static void chatterPost(id scaReviewHistoryId, String message) {
    List<ConnectApi.BatchInput> lstBatchInputs = new List<ConnectApi.BatchInput>();
    // clang-format off
    for (SCA_Review_History__c scaReviewHistoryRecord : [
         SELECT id,CreatedById, Branch__c
         FROM SCA_Review_History__c
         WHERE
          id =:scaReviewHistoryId
         WITH SECURITY_ENFORCED
    ]) {
      // clang-format on
      ConnectApi.FeedItemInput input =
          new FlosumChatterBuilder()
              .setSubjectId(scaReviewHistoryRecord.Branch__c)
              .addMention(scaReviewHistoryRecord.CreatedById)
              .setVisibility(ConnectApi.FeedItemVisibilityType.InternalUsers)
              .addText(' ' + message)
              .getFeedItem();
      // Creating batch input instance using FeedItemInput and adding it to
      // lstBatchInputs
      ConnectApi.BatchInput batchInput = new ConnectApi.BatchInput(input);
      lstBatchInputs.add(batchInput);
      if (!Test.isRunningTest()) {
        ConnectApi.ChatterFeeds.postFeedElementBatch(Network.getNetworkId(), lstBatchInputs);
      }
    }
  }
}